import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-grey-100 md:px-0 xl:px-20 items-center justify-center h-screen">
        <Nav />
        <div className="flex-1 pt-20 ">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
